# Generated by Django 3.0.8 on 2020-07-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=119)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=9999)),
                ('summary', models.TextField()),
            ],
        ),
    ]
